# List products -- Query Params: page, order_by={-price, price}
GET http://localhost:8080/product/

# Create product
POST http://localhost:8080/product/
{
  "name": "Bose Soundbar 300 TV Ses Sistemi, Siyah",
  "price": 10.099,
  "description": "Akustik performans: Beş tam-kapsamlı sürücü TV'nize, filmlerinize, oyunlarınıza ve daha fazlasına mükemmel sesi katmak için geniş sahneli ve net ses üretir",
  "currency": "TRY",
  "seller_id": "abh63gsq74i",
  "in_stock": true,
  "delivery_options": [
    {
      "name": "Yurtiçi Kargo",
      "price": 9.99,
      "currency": "TRY"
    },
    {
      "name": "MNG KARGO",
      "price": 8.11,
      "currency": "TRY"
    }
  ]
}

# Get product by id
GET http://localhost:8080/product/1/

# Update product
PUT http://localhost:8080/product/1/
{
  "name": "Bose Soundbar 300 TV Ses Sistemi, Beyaz",
  "delivery_options": [
    {
      "name": "Yurtiçi Kargo",
      "price": 9.99,
      "currency": "TRY"
    },
    {
      "name": "MNG KARGO",
      "price": 8.11,
      "currency": "TRY"
    },
    {
      "name": "Aras Kargo",
      "price": 7.11,
      "currency": "TRY"
    }
  ]
}
